name: 'Postman Collection Workflow'

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:               
   # - cron: 30 02 * * *   # 8am IST every day
   # - cron: 00 14 * * *   # 7.30pm IST every day
    - cron: 00 06 * * 1-5 # 11.30am IST Monday to Friday

jobs:
  run-postman-tests:
      runs-on: ec2-github-runner

      steps:
          - name: Checkout the code
            uses: actions/checkout@v5.0.0

          - name: Install NodeJs and npm
            uses: actions/setup-node@v3.9.1
            with:
              node-version: '22'

          - name: Install Newman and HTML-extra globally
            run: |
                  npm install -g newman
                  npm install -g newman-reporter-htmlextra

          - name : Run Postman Collection with newman
            run: |
                newman run 'In Warranty Flow CollectionFor CLI_external data.postman_collection.json' \
                -e QA.postman_environment.json \
                -d testdata.csv \
                -r cli,htmlextra \
                --reporter-htmlextra-export ./newman/index.html \
                --reporter-cli-no-truncate

          - name: Newman Report
            if: always() #ensure that the archieve executed irrespective whether the previous step has passed or not
            uses: actions/upload-artifact@v4.6.2
            with:
                name: Newman Report
                path: newman/*.html
                
          - name: Creating GitHub Page Branch
            if: always()
            uses: peaceiris/actions-gh-pages@v4.0.0
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: newman/

          - name: Send Email Notifications
            if: always()
            uses: dawidd6/action-send-mail@v6
            with:
              server_address: smtp.gmail.com
              server_port: 465
              username: ${{ secrets.EMAIL_USERNAME }}
              password: ${{ secrets.EMAIL_PASSWORD }}
              subject: "Pheonix Inwarranty Flow Test Executions"
              to: "priyapethe3@gmail.com"
              from: "<${{ secrets.EMAIL_USERNAME }}>"
              body: |
                  Hello Team,

                  Pheonix Inwarranty Flow tests has been executed. The Report has been published and
                  the URL is : https://vvaidya6.github.io/Inwarranty-Flow-Collection/

                  
                  Regards,
                  Vaibhav Vaidya
                  
            
          
  
